config/routes.rb
PhcdevworksPortfolio::Engine.routes.draw do

  # Project Routes
  namespace :project do
    resources :posts, class_name: "Project::Post"
    resources :types, class_name: "Project::Type"
    resources :pages, only: [:index, :show]
  end
  
  # Mount Routes
  mount PhcdevworksAccounts::Engine, :at => '/'
  mount PhcdevworksCoreModules::Engine, :at => '/'

end

app/models/phcdevworks_portfolio/project.rb
module PhcdevworksPortfolio
  module Project
    def self.table_name_prefix
      'phcdevworks_portfolio_project_'
    end
  end
end

app/models/phcdevworks_portfolio/project/post.rb
module PhcdevworksPortfolio
  class Project::Post < ApplicationRecord

    # Clean URL Initialize
    extend FriendlyId

    # Paper Trail Initialize
    has_paper_trail :class_name => 'PhcdevworksPortfolio::ProjectPostVersions'

    # Image Upload
    has_one_attached :project_post_image

    # Relationships
    belongs_to :user, class_name: "PhcdevworksAccounts::User"
    has_and_belongs_to_many :types, class_name: "PhcdevworksPortfolio::Project::Type", :join_table => "phcdevworks_portfolio_project_posts_types", :dependent => :destroy
    has_and_belongs_to_many :categories, class_name: "PhcdevworksCoreModules::Post::Category", :join_table => "phcdevworks_portfolio_project_categories_posts", :dependent => :destroy
    belongs_to :optimization, class_name: "PhcdevworksCoreModules::Marketing::Optimization", optional: true

    # Clean URL Define
    friendly_id :project_post_nice_urls, use: [:slugged, :finders]

    def project_post_nice_urls
      [:project_post_title]
    end

  end
end

app/models/phcdevworks_portfolio/project/type.rb
module PhcdevworksPortfolio
  class Project::Type < ApplicationRecord

    # Clean URL Initialize
    extend FriendlyId

    # Paper Trail Initialize
    has_paper_trail :class_name => 'PhcdevworksPortfolio::ProjectTypeVersions'

    # Relationships
    belongs_to :user, class_name: "PhcdevworksAccounts::User"
    has_and_belongs_to_many :posts, class_name: "Project::Post", :join_table => "phcdevworks_portfolio_project_posts_types", :dependent => :destroy

    # Clean URL Define
    friendly_id :project_type_nice_urls, use: [:slugged, :finders]

    def project_type_nice_urls
      [:project_type_name]
    end

  end
end

app/controllers/phcdevworks_portfolio/project/pages_controller.rb
require_dependency "phcdevworks_portfolio/application_controller"

module PhcdevworksPortfolio
  class Project::PagesController < ApplicationController

    # Layout
    layout "phcdevworks_portfolio/frontend"

    # INDEX
    def index
      @phcdevworks_projects_index = Project::Post.where(project_post_status: "published").order("project_post_title ASC")
      @phcdevworks_projects_randomizer = Project::Post.order('RANDOM()').limit(1)
    end

    # SHOW
    def show
      @phcdevworks_projects_single = Project::Post.friendly.find(params[:id])
    end

  end
end

app/controllers/phcdevworks_portfolio/project/posts_controller.rb
require_dependency "phcdevworks_portfolio/application_controller"

module PhcdevworksPortfolio
  class Project::PostsController < ApplicationController

    # Filters & Security
    #include PhcdevworksCore::PhcpluginsHelper
    before_action :authenticate_user!
    before_action :set_paper_trail_whodunnit
    before_action :set_project_post, only: [:edit, :update, :destroy]

    # GET /project/posts
    def index
      @project_posts = Project::Post.all.order("project_post_title ASC")
    end

    # GET /project/posts/new
    def new
      @project_post = Project::Post.new
    end

    # GET /project/posts/1/edit
    def edit
    end

    # POST /project/posts
    def create
      @project_post = Project::Post.new(project_post_params)
      @project_post.user_id = current_user.id
      @project_post.org_id = current_user.org_id
      respond_to do |format|
        if @project_post.save
          format.html { redirect_to project_posts_path, :flash => { :success => 'Project Post has been Added.' }}
          format.json { render :show, status: :created, location: @project_post }
        else
          format.html { render :new }
          format.json { render json: @project_post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /project/posts/1
    def update
      respond_to do |format|
        if @project_post.update(project_post_params)
          format.html { redirect_to project_posts_path, :flash => { :notice => 'Project Post has been Updated.' }}
          format.json { render :show, status: :ok, location: @project_post }
        else
          format.html { render :edit }
          format.json { render json: @project_post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /project/posts/1
    def destroy
      @project_post.destroy
      respond_to do |format|
        format.html { redirect_to project_posts_path, :flash => { :error => 'Project Post has been Removed.' }}
        format.json { head :no_content }
      end
    end

    private

    # Common Callbacks
    def set_project_post
      @project_post = Project::Post.find(params[:id])
    end

    # Whitelist
    def project_post_params
      params.require(:project_post).permit(:project_post_title, :project_post_description, :project_post_url, :project_post_type, :project_post_status, :project_post_image, :project_post_images, :slug, :optimization_id, :user_id, :org_id, category_ids: [], type_ids: [])
    end

  end
end

app/controllers/phcdevworks_portfolio/project/types_controller.rb
require_dependency "phcdevworks_portfolio/application_controller"

module PhcdevworksPortfolio
  class Project::TypesController < ApplicationController

    # Filters & Security
    #include PhcdevworksCore::PhcpluginsHelper
    before_action :authenticate_user!
    before_action :set_paper_trail_whodunnit
    before_action :set_project_type, only: [:edit, :update, :destroy]

    # GET /project/types
    def index
      @project_types = Project::Type.all
    end

    # GET /project/types/new
    def new
      @project_type = Project::Type.new
    end

    # GET /project/types/1/edit
    def edit
    end

    # POST /project/types
    def create
      @project_type = Project::Type.new(project_type_params)
      @project_type.user_id = current_user.id
      @project_type.org_id = current_user.org_id
      respond_to do |format|
        if @project_type.save
          format.html { redirect_to project_types_path, :flash => { :success => 'Project Type has been Added.' }}
          format.json { render :show, status: :created, location: @project_type }
        else
          format.html { render :new }
          format.json { render json: @project_type.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /project/types/1
    def update
      respond_to do |format|
        if @project_type.update(project_type_params)
          format.html { redirect_to project_types_path, :flash => { :notice => 'Project Type has been Updated.' }}
          format.json { render :show, status: :ok, location: @project_type }
        else
          format.html { render :edit }
          format.json { render json: @project_type.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /project/types/1
    def destroy
      @project_type.destroy
      respond_to do |format|
        format.html { redirect_to project_types_path, :flash => { :error => 'Project Type has been Removed.' }}
        format.json { head :no_content }
      end
    end

    private

    # Common Callbacks
    def set_project_type
      @project_type = Project::Type.find(params[:id])
    end

    # Whitelist
    def project_type_params
      params.require(:project_type).permit(:project_type_name, :slug, :user_id, :org_id)
    end

  end
end

app/helpers/phcdevworks_portfolio/project/pages_helper.rb
module PhcdevworksPortfolio
  module Project::PagesHelper
  end
end

app/helpers/phcdevworks_portfolio/project/posts_helper.rb
module PhcdevworksPortfolio
  module Project::PostsHelper
  end
end

app/helpers/phcdevworks_portfolio/project/types_helper.rb
module PhcdevworksPortfolio
  module Project::TypesHelper
  end
end

app/views/phcdevworks_portfolio/project/posts/_form.html.erb
<!-- Form - Project - Posts -->
<%= form_with(model: project_post, local: true) do |form| %>

    <!-- PHCNotifi Render Validation -->
    <%= render "phcdevworks_notifications/bootstrap/validations", :object => @project_post %>
    <!-- PHCNotifi Render Validation -->

    <!-- Form Input Fields -->
    <div class="form-group field_with_errors">
        <%= form.label :project_post_title, "Project Title" %>
        <%= form.text_field :project_post_title, placeholder: "Project Title", class: "form-control" %>
    </div>

    <div class="form-group field_with_errors">
        <%= form.label :project_post_description, "Project Description" %>
        <%= form.text_area :project_post_description, placeholder: "Project Description", class: "form-control editor" %>
    </div>

    <div class="form-group field_with_errors">
        <%= form.label :project_post_url, "Project URL" %>
        <%= form.text_field :project_post_url, placeholder: "Project URL", class: "form-control" %>
    </div>

    <div class="form-group field_with_errors">
        <%= form.label :project_post_status, "Project Status" %>
        <%= form.select( :project_post_status, [["Draft","draft"],["Published","published"],["Review","review"]], {}, {class: "form-control"}) %>
    </div>

    <div class="form-group field_with_errors">
        <%= form.label :project_post_image, "Project Image" %>
        <%= form.file_field :project_post_image, class: "form-control" %>
    </div>
    <% if form.object.project_post_image.attached? %>
        <%= image_tag main_app.url_for(form.object.project_post_image), class: "img-responsive img-thumbnail" %>
    <% end %>

    <div class="form-check">
        <%= form.collection_check_boxes :type_ids, PhcdevworksPortfolio::Project::Type.all, :id, :project_type_name do |project_type| %>
            <%= project_type.check_box class: "form-check-input" %>
            <%= project_type.label class: "form-check-label" %>
        <% end %>
	</div>

    <div class="form-check">
        <%= form.collection_check_boxes :category_ids, PhcdevworksCoreModules::Post::Category.all, :id, :post_category_name do |post_category| %>
        	<%= post_category.check_box class: "form-check-input" %>
        	<%= post_category.label class: "form-check-label" %>
        <% end %>
	</div>

	<div class="form-group">
		<label>Attach SEO Data</label>
		<%= collection_select(:project_post, :optimization_id, PhcdevworksCoreModules::Marketing::Optimization.order("marketing_optimization_page_title"), :id, :marketing_optimization_page_title, {}, {class: "form-control"}) %>
	</div>
    <!-- Form Input Fields -->

    <!-- Form Submition Button -->
    <div class="actions">
        <%= form.submit class: "btn btn-primary" %>
    </div>
    <!-- For Submition Button -->

<% end %>
<!-- Form - Project - Posts -->

app/views/phcdevworks_portfolio/project/posts/edit.html.erb
<!-- PHCTitleSEO Title Variables -->
<% phc_title "Portfolio Manager" %>
<% phc_title_tagline "Update Project Post" %>
<% phc_breadcrumb_one link_to "Project List", phcdevworks_portfolio.project_posts_path %>
<% phc_breadcrumb_two yield(:phc_title_tagline) %>
<!-- PHCTitleSEO Title Variables -->

<!-- Page Bradcrumbs -->
<ol class="breadcrumb pull-right">
	<li class="breadcrumb-item"><%= yield(:phc_breadcrumb_one) %></li>
	<li class="breadcrumb-item active"><%= yield(:phc_breadcrumb_two) %></li>
</ol>
<!-- Page Bradcrumbs -->

<!-- Page Header -->
<h2 class="page-header"><%= yield(:phc_title) %></h2>
<!-- Page Header -->

<!-- Page Content -->
<div class="row">
	<div class="col-lg-12">

		<!-- Panel -->
		<div class="panel panel-inverse">

			<!-- Panel - Heading -->
			<div class="panel-heading">
				<h4 class="panel-title"><%= yield(:phc_title) %></h4>
			</div>
			<!-- Panel - Heading -->

			<!-- Panel - Body -->
			<div class="panel-body">

			    <!-- Edit Form -->
                <%= render "form", project_post: @project_post %>
				<!-- Edit Form -->

			</div>
			<!-- Panel - Body -->

		</div>
		<!-- Panel -->

	</div>
</div>
<!-- Page Content -->

app/views/phcdevworks_portfolio/project/posts/index.html.erb
<!-- PHCTitleSEO Title Variables -->
<% phc_title "Portfolio Manager" %>
<% phc_title_tagline "Project Post Index" %>
<% phc_breadcrumb_one link_to "Project List", phcdevworks_portfolio.project_posts_path %>
<% phc_breadcrumb_two yield(:phc_title_tagline) %>
<!-- PHCTitleSEO Title Variables -->

<!-- Page Bradcrumbs -->
<ol class="breadcrumb pull-right">
	<li class="breadcrumb-item"><%= yield(:phc_breadcrumb_one) %></li>
	<li class="breadcrumb-item active"><%= yield(:phc_breadcrumb_two) %></li>
</ol>
<!-- Page Bradcrumbs -->

<!-- Page Header -->
<h2 class="page-header"><%= yield(:phc_title) %></h2>
<!-- Page Header -->

<!-- Page Content -->
<div class="row">
	<div class="col-lg-12">

		<!-- Panel -->
		<div class="panel panel-inverse">

			<!-- Panel - Heading -->
			<div class="panel-heading">
				<h4 class="panel-title"><%= yield(:phc_title) %></h4>
			</div>
			<!-- Panel - Heading -->

			<!-- Panel - Body -->
			<div class="panel-body">

				<!-- Index - Table -->
				<div class="table-responsive">
					<table class="table table-striped table-bordered">

                        <thead>
                            <tr>
                                <th>Project Title</th>
                                <th>Project Description</th>
                                <th>Project Status</th>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody>
                            <% @project_posts.each do |project_post| %>
                                <tr>
                                    <td><%= project_post.project_post_title %></td>
									<td><%= truncate(project_post.project_post_description, :length => 80, :escape => false) %></td>
                                    <td><%= project_post.project_post_status.capitalize %></td>
                                    <td>
                                        <div class="btn-group d-flex" role="group">
                                            <%= link_to "Update Project", edit_project_post_path(project_post), class: "btn btn-purple btn-xs" %>
                                            <%= link_to "Remove Project", project_post, method: :delete, data: { confirm: "Are you sure? This will also remove the Members addresses and listings. This action cannot be reversed." }, class: "btn btn-danger btn-xs" %>
                                        </div>
                                    </td>
                                </tr>
    						<% end %>
						</tbody>

					</table>
				</div>
				<!-- Index - Table -->

				<!-- New Button -->
				<%= link_to phcdevworks_portfolio.new_project_post_path, class: "btn btn-primary btn-sm" do %>
					<i class="fad fa-plus-circle"></i>
					Add a New Project
				<% end %>
				<!-- New Button -->

			</div>
			<!-- Panel - Body -->

		</div>
		<!-- Panel -->

	</div>
</div>
<!-- Page Content -->

app/views/phcdevworks_portfolio/project/posts/new.html.erb
<!-- PHCTitleSEO Title Variables -->
<% phc_title "Portfolio Manager" %>
<% phc_title_tagline "Update Project Post" %>
<% phc_breadcrumb_one link_to "Project List", phcdevworks_portfolio.project_posts_path %>
<% phc_breadcrumb_two yield(:phc_title_tagline) %>
<!-- PHCTitleSEO Title Variables -->

<!-- Page Bradcrumbs -->
<ol class="breadcrumb pull-right">
	<li class="breadcrumb-item"><%= yield(:phc_breadcrumb_one) %></li>
	<li class="breadcrumb-item active"><%= yield(:phc_breadcrumb_two) %></li>
</ol>
<!-- Page Bradcrumbs -->

<!-- Page Header -->
<h2 class="page-header"><%= yield(:phc_title) %></h2>
<!-- Page Header -->

<!-- Page Content -->
<div class="row">
	<div class="col-lg-12">

		<!-- Panel -->
		<div class="panel panel-inverse">

			<!-- Panel - Heading -->
			<div class="panel-heading">
				<h4 class="panel-title"><%= yield(:phc_title) %></h4>
			</div>
			<!-- Panel - Heading -->

			<!-- Panel - Body -->
			<div class="panel-body">

				<!-- New Form -->
                <%= render "form", project_post: @project_post %>
				<!-- New Form -->

			</div>
			<!-- Panel - Body -->

		</div>
		<!-- Panel -->

	</div>
</div>
<!-- Page Content -->